version: "3" # To Deploy on swarm mode (See NOT SUPPORTED FOR DOCKER STACK DEPLOY)
services:
  server:
    image: perf-image:v2
    command: bash -c "ServerGRPC"
  client:
    image: perf-image:v2
    volumes:
      - /home/$USER/Output/grpc_client:/go/src/app
    command: bash -c "ClientGRPC $$IPSERVER $$NUMBER >> log_client.csv"
    depends_on:
      - server
    environment:
      - IPSERVER=server # We got the ip like this
      - NUMBER=5